const mongoose=require("mongoose");

const courseSchema= new mongoose.Schema({
  courseName:{
    type:String,
    required:true
  },
  courseDescription:{
    type:String,
    required:true
  },
  instructor:{
    type:mongoose.Schema.Types.ObjectId,
    ref:"user",
    required:true
  },
  whatYouWillLearn:{
    type:String,
    required:true
  },
  courseContent:[
    {
        type:mongoose.Schema.Types.ObjectId,
        ref:"section"
    }
  ],
  ratingAndReviews:[
    {
    type:mongoose.Schema.Types.ObjectId,
    ref:"ratingAndReview"
  }
],
  price:{
    type:Number,
  },
  thumbnail:{
    type:String
  },
  tag:{
    type:[String],
    required:true
  },
  category:{
    type:mongoose.Schema.Types.ObjectId,
    ref:"category"
  },
  studentEnrolled:[{
    type:mongoose.Schema.Types.ObjectId,
    required:true,
    ref:"user"
  }],
  instructions:{
    type:[String]
  },
  status:{
    type:String,
    enum:["Draft","Published"]
  },
  createdAt:{
    type:Date,
    default:Date.now
  } 
  
});

module.exports=mongoose.model("course",courseSchema);